name: build-shared
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 
      - name: Configure MSVC developer console
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      # - name: Configure mingw
      #   if: matrix.os == 'windows-latest'
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     install: >-
      #       mingw-w64-x86_64-gcc
      #       make
      - name: Build artifacts
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            nmake /F Makefile.msvc build_shared
            # make -f Makefile.mingw build_shared
          } else {
            make build_shared
          }

          New-Item -ItemType Directory -Path artifacts -Force

          if ($env:RUNNER_OS -eq "macOS") {
            $arch = & uname -m
            if ($arch -eq "arm64") {
              New-Item -ItemType Directory -Path artifacts/macos_arm64 -Force
              mv libpg_query.dylib artifacts/macos_arm64/libpg.dylib
            } else {
              New-Item -ItemType Directory -Path artifacts/macos_x86_64 -Force
              mv libpg_query.dylib artifacts/macos_x86_64/libpg.dylib
            }
          } else {
            if (Test-Path libpg_query.so) {
              mv libpg_query.so artifacts/
            }

            if (Test-Path libpg_query.dll) {
              mv libpg_query.dll artifacts/
            }
          }
        shell: pwsh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: artifacts
          retention-days: 1
          overwrite: true
  combine:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
          merge-multiple: true
      - name: Upload single zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-all
          path: final-artifacts.zip
          retention-days: 1
